### ISSUE TITLE
Add support for BIP 44

### ISSUE THREAD

**Issue by isaacvr** [fibercrypto/skywallet-protob#65]
**Is your feature request related to a problem? Please describe.**
We are adding support for [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki), so we need support for this in the protocol.

**Describe the solution you'd like**
Define a new message field with the required BIP44 information.

**Additional context**
https://github.com/skycoin/hardware-wallet/pull/340

**Implementation steps**

- ~Add BIP 44 address index in `SkycoinAddress`~
- Keep `SkycoinAddress` for deterministic wallet address generation exactly as it was prior to work starting this issue
- ~Add generic firmware message for address generation given BIP 44 index~
- [x] Add BIP 44 address index in  `SkycoinSignMessage`
- [x] Add BIP 44 address index in `SkycoinTransactionInput`
- [x] Add BIP 44 address index in `SkycoinTransactionOutput`
- [x] Add BIP 44 address index in `SignTx` and derived message types

**Comment by olemis** [comment]
@stdevAdrianPaez the rest is for you

**Comment by olemis** [comment]
what is missing is BIP44 support for long transactions .

**Comment by olemis** [comment]
@stdevAlDen I updated issue description to pivot on changes applied upon `SkycoinAddress` message.

**Comment by olemis** [comment]
fixed in f45d182
